name: shiny-app           # Environment name
channels:
  - defaults              # Default Conda channel
  - conda-forge           # Additional channel for extra packages
dependencies:
  - python=3.10           # Specify the version of Python
  - pandas                # For data manipulation
  - matplotlib            # For plotting
  - shiny                 # For building Shiny apps
